png("plot3.png", width = 480, height = 480)
plot(datetime, electricpowernew$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(datetime, electricpowernew$Sub_metering_2, col = "red")
lines(datetime, electricpowernew$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 2, legend = c("Sub Metering 1", "Sub Metering 2", "Sub Metering 3"))
dev.off()
